industrial-optimization-group/DESDEO

- desdeo/problem/toy/__init__.py
- desdeo/problem/toy/river_pollution_robust.py
- examples/riverrobust.py
Added an example and a toy problem (based on river pollution) for solving problems with decision uncertainty.
> decision uncertainty example

- desdeo/preference/__init__.py
- desdeo/preference/direct.py
- desdeo/preference/nimbus.py
- desdeo/problem/toy/river_pollution_robust.py
- examples/riverrobust.py
Fixed warning reported by flake8 and isort. The build should now be passing.
> Fixed flake8 and isort warnings. Build should now be passing.

- docs/index.rst
- docs/introduction.rst
- poetry.lock
- pyproject.toml
> Added desdeo-emo to the package and bumped version

- .gitignore
- README.md
- pyproject.toml
> Add CPU-based rules for dependency choice

- desdeo/problem/schema.py
- pyproject.toml
- tests/example_problem.json
> Light-weaver/issue69

- desdeo/problem/__init__.py
- desdeo/problem/testproblems.py
- desdeo/tools/__init__.py
- desdeo/tools/pyomo_solver_interfaces.py
- tests/test_pyomo_solvers.py
I added a create_pyomo_gurobi_solver() function under pyomo solver interfaces to facilitate using gurobi through pyomo
> Desdeo2 gurobi

- desdeo/mcdm/pareto_navigator.py
- docs/howtoguides/pareto_navigator.md
Dokumentaatiota Pareto Navigatorin implementaatiolle.
> Pareto navigator

- desdeo/tools/scipy_solver_interfaces.py
Corrected an error stemming from giving initial_guess (x0) to scipy_minimize as a dict instead of a list.
> Correct an error in scipy_solver_interfaces.

- desdeo/mcdm/nautili.py
- desdeo/mcdm/nautilus.py
- desdeo/mcdm/nautilus_navigator.py
- desdeo/mcdm/nimbus.py
- desdeo/tools/__init__.py
- desdeo/tools/generics.py
- desdeo/tools/gurobipy_solver_interfaces.py
- desdeo/tools/ng_solver_interfaces.py
- desdeo/tools/proximal_solver.py
- desdeo/tools/pyomo_solver_interfaces.py
- desdeo/tools/scipy_solver_interfaces.py
- desdeo/tools/utils.py
- tests/test_nimbus.py
Removed CreateSolverType and added BaseSolver as a base class for all solvers to generics.py as requested in issue #118. I replaced every reference to CreateSolverType (that I could find) and replaced them with BaseSolver (for docstrings as well). Also renamed python variables called "create_solver" as just "solver" to avoid confusion. Ran all the tests and did not see any errors caused by these changes.
> Removed CreateSolverType and added BaseSolver as a base class for all solvers.

- desdeo/problem/gurobipy_evaluator.py
- desdeo/tools/gurobipy_solver_interfaces.py
In gurobi, when there are no solutions, it will throw errors when trying to get vars and constraints from model so if there is no solutions, just simply return empty dict.
> Gurobi check number of sols before parsing

- desdeo/problem/testproblems.py
- desdeo/tools/__init__.py
- desdeo/tools/utils.py
Added an implementation of the payoff table method. No tests for it yet, but probably should be added.
> Payoff table method

- desdeo/problem/pyomo_evaluator.py
- desdeo/problem/schema.py
- tests/test_json_parser.py
- tests/test_schema_tensors.py
Fixed and tested schema to support initialization of Tensor variables and constants with a single value for bounds and current values.
Updated the json parser tests for pyomo to check that matrix operations with column and row vectors work as intended.
> Problem schema and tests updated.

- desdeo/problem/testproblems.py
- tests/test_testproblems.py
Added the data file paths as an argument for the forest problem. The data files may be in different directory, so now the paths to those files is given as a list argument for the problem.
> Added the data file paths as arguments for the forest problem.

- desdeo/problem/testproblems.py
- docs/explanation/test_problems.md
Documentation about the UTOPIA forest problem. First some general info and the problem definition, then something about the implementation, and finally how to use the problem in testing.
> Forest problem documentation

- desdeo/api/db_models.py
- New table **GSolutionArchive** which is quite similar to  **SolutionArchive** table. Differences: 
1. column **to_vote** for marking the solution that needs further voting
2. column **decision_variables** saves data as json to work with problems with tensor variables.
> Db structure for gnimbus solutions

- desdeo/problem/__init__.py
- desdeo/problem/utils.py
Util to convert tensor variable to numpy array for `solve_intermediate_solutions()`
> Add util for tensor var

- desdeo/tools/utils.py
- tests/test_tools_utils.py
Added some missing checks for solvers into guess_best_solver and fixed the test for find_compatible_solvers.
> Fixing guess_best_solver

- desdeo/mcdm/nautili.py
- desdeo/mcdm/nautilus_navigator.py
- desdeo/problem/testproblems.py
- tests/test_nautili.py
- tests/test_nautilus.py
- tests/test_scalarization.py
added if sentence for nautili to use diff. asf when diff problem. 
Also, fixed tests related to river_pollution problem as now we maximize the first 4 objectives. Old tests where assuming to minimize these.
Also, added is_twice_differentiable=True, to binh and korn problem definition because it is and the automatic way does not work (is it supposed to)?
also, removed a '#' from comments as it was somewhere as double '##'
> fixes to nautili and nautilus family tests

- docs/api/desdeo_problem.md
- docs/explanation/index.md
- docs/explanation/parsing_and_evaluating.md
- docs/explanation/simulator_support.md
- docs/howtoguides/problem.md
- mkdocs.yml
- Documentation for the evaluator for simulator and surrogate based problems and an example on how to use it
- Documentation for simulator files and an example of a simulator file (this file is meant for explaining things needed for simulator and surrogate based problems and so if there is something to be said about surrogates, it can be added here)
- How to guides for defining simulator and surrogate based problems in DESDEO
> Simulator and surrogate support documentation

- desdeo/problem/testproblems.py
+ added explicit problem information to the problem definitions
> added zdt2 and zdt3 test problems

- desdeo/tools/scalarization.py
- desdeo/tools/utils.py
scalarization.py refactored to use ideal and nadir points from arguments if possible, two new functions added to utils.py which return only corrected ideal or nadir points
> scalarization.py refactored to use optional ideal and nadir points

- desdeo/tools/scipy_solver_interfaces.py
created pydantic models in order to pass solver parameters.
> refactoring scipyDeSolver and scipyMinimizeSolver options

- desdeo/tools/indicators_unary.py
- tests/test_indicators.py
Implementation of the IGD+ indicator with a geometric average.
> IGD+ indicator

- desdeo/problem/testproblems/forest_problem.py
- desdeo/problem/testproblems/river_pollution_problem.py
- desdeo/problem/testproblems/spanish_sustainability_problem.py
Fixed data paths for test problems:
* `forest_problem_discrete`
* `river_pollution_problem_discrete`
* `spanish_sustainability_problem_discrete`
> test problem data path fix

- docs/explanation/simulator_support.md
- docs/howtoguides/problem.md
Replaced the old example of a simulator file with the example used in the DESDEO2 paper. Also, fixed some typos in the documentation for the simulator stuff.
> Documentation changes for the simulator stuff

- desdeo/tools/indicators_unary.py
- tests/test_indicators.py
Implementation of R-metric indicator.
> R-metric indicator

- desdeo/tools/scalarization.py
- tests/test_scalarization.py
Scalarization function added. 
**Unittests needs to be revised as the non differentiable version sometimes fails (possibly caused by the solver or wrong solver options...).**
> scenario based problems scalarization function added

- desdeo/problem/testproblems/__init__.py
- desdeo/problem/testproblems/mcwb_problem.py
- tests/test_testproblems.py
Added mcwb problems from https://www.mdolab.net/Ray/Research-Data/mcwb_problem.zip class mcwb_concepts.py.
> Mcwb test problem

- desdeo/emo/operators/mutation.py
- tests/test_ea.py
Makinen, Periaux and Toivanen mutation: [article](https://users.jyu.fi/~rainom/pub/fluid99.pdf)
> MPT-mutation

- desdeo/emo/operators/mutation.py
- tests/test_ea.py
Non-uniform mutation: [article](https://doi.org/10.1016/j.amc.2007.03.046).
> Non-uniform mutation

- desdeo/emo/operators/mutation.py
- tests/test_ea.py
Self-adaptive Gaussian mutation: [article](https://doi.org/10.1109/4235.771163), Section II, step 3)
> Self adaptive Gaussian mutation

- desdeo/api/app.py
- desdeo/api/models/__init__.py
- desdeo/api/models/nimbus.py
- desdeo/api/models/state.py
- desdeo/api/routers/nimbus.py
- desdeo/api/tests/test_routes.py
- NIMBUSClassificationRequest
- NIMBUSClassificationState
- endpoint method/nimbus/solve
> feat: 2 models and router for nimbus

- webui/src/app.css
- webui/src/lib/components/ui/topbar/Topbar.svelte
- webui/src/routes/dashboard/+page.svelte
- webui/src/routes/home/+page.svelte
- webui/src/routes/problem/+page.svelte
(GUI) Implementation of the login screen and an initial version of the dashboard. To avoid conflicts with Giovanni´s existing code for the login screen, I added mine to webui/src/routes/home.
> (GUI) add Topbar component and implement dashboard and home pages

- desdeo/api/models/user.py
- desdeo/api/routers/user_authentication.py
- desdeo/api/tests/test_routes.py
Decision makers and analysts can now be added to the database through FastAPI endpoints
Also small fix: .schema -> .problem in user.py.
> feat: can add users now

- docs/tutorials/contributing.md
"developed my researchers" -> "developed by researchers"
> Fixed excactly one typo

- desdeo/tools/indicators_unary.py
- pyproject.toml
- I [compared](https://github.com/laitozz/DESDEO/commit/e70a862) the moocore and pymoo implementations and they seem to be equal down to rounding error.
> Update the hypervolume indicator to utilize moocore instad of pymoo

- desdeo/api/routers/_NIMBUS.py
- desdeo/api/tests/test_models.py
- desdeo/tools/pyomo_solver_interfaces.py
- desdeo/tools/utils.py
- desdeo/utopia_stuff/utopia_problem.py
- desdeo/utopia_stuff/utopia_problem_old.py
- tests/test_tools_utils.py
* Update the dictionary accesses accordingly. 
* Move the default values for the cbc solver to the pydantic model instead of _default_cbc_options.
> Add solver option classes to the available_solvers dictionary

- webui/src/lib/components/custom/preferences-bar/preferences-sidebar.svelte
- webui/src/routes/interactive_methods/EMO/+page.svelte
- webui/src/routes/interactive_methods/EMO/+page.ts
- webui/src/routes/interactive_methods/NIMBUS/+page.svelte
This pull request introduces updates to the user interface and backend logic for interactive methods in the web application. The changes focus on improving preference selection, enhancing the solution explorer, and refining data fetching mechanisms.
* Modified the `preferences-sidebar.svelte` file to include new preference types (`Classification`) and updated descriptions for `Reference point` preferences. This improves clarity and expands the options available to users. [[1]](diffhunk://#diff-aa70a281a6aae8d9092d3b24b8afaeffc31982dda5a235e7a25f687d43971bd1L59-R62) [[2]](diffhunk://#diff-aa70a281a6aae8d9092d3b24b8afaeffc31982dda5a235e7a25f687d43971bd1R86-R89)
* Updated the `AppSidebar` component in `NIMBUS/+page.svelte` to use the `Classification` preference type instead of `Reference …
> Changes in layout for EMO method and correction in preference type of NIMBUS

- desdeo/mcdm/gnimbus.py
- tests/test_gnimbus.py
also added this to the tests. So tests should run with pytest.raises(exception) and if this fails, then the exception was not raised (and it should).
> feature: added GNIMBUS error and check for valid classification

- desdeo/problem/testproblems/cake_problem.py
can be added to databases through other means.
> removed the db adder function. 
